# Generated by Django 3.2.8 on 2023-11-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('planting_season', models.CharField(max_length=50)),
                ('regions', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=50)),
            ],
        ),
    ]
